#!/bin/sh

# Autostart

## Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

## Autokill
killall -9 ksuperkey xfce4-power-manager &
killall sxhkd; sxhkd &
killall dunst; dunst &

## Compositor
picom -b &

## Background
$HOME/.config/bspwm/wallpapers &

## Redshift (Optional)
# redshift -x && redshift -O 4000k &

# Start nm and blueman system tray
exec nm-applet &
exec blueman-applet &


# Xinput
xinput set-prop "ELAN1201:00 04F3:3098 Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "ELAN1201:00 04F3:3098 Touchpad" "libinput Natural Scrolling Enabled" 1
xinput set-prop "ELAN1201:00 04F3:3098 Touchpad" "libinput Disable While Typing Enabled" 0

## Fix Cursor
xsetroot -cursor_name left_ptr &

## Bar
$HOME/.config/polybar/launch.sh &

## Super Key
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

## Mpd
exec mpd &

# Variable

alias bc='bspc config'
alias br='bspc rule'

# Workspaces

bspc monitor -d 1 2 3 4 5 6 7 8

# Config

bc border_width 1
bc window_gap 10
bc split_ratio 0.52
bc bottom_padding 0
bc top_padding 10

bc gapless_monocle true
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true
bc paddingless_monocle true
bc single_monocle false

bspc config focused_border_color        "#2FDE73"
bspc config normal_border_color         "#101313"
bspc config active_border_color         "#101313"
bspc config presel_feedback_color	"#008ce3"
# Rules

br -a feh state=floating
br -a sxiv state=floating
br -a mpv state=floating
br -a Conky state=floating
br -a stalonetray state=floating
br -a Lxappearance state=floating
bc -a Pavucontrol state=floating center=true
bc -a '*:blueman-manager' state=floating center=true
bc -a Nm-connection-editor state=floating
bc -a spectacle floating=on follow=on
bc -a 'Android Emulator *' state=floating
bc -a VirtualBox Manager state=fullscreen
bc -a VirtualBox Machine state=fullscreen
